version: "3.9"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.99.0/24
    

services:  
  # nginx
  web:
    image: nginx:1.25.1-alpine
    container_name: web
    restart: unless-stopped
    ports: 
      - "8080:80"
    volumes:
      - ../php/src/html:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      default:
        aliases:
          - mis_network
  
  php-fpm:
    image: php:8.2.5-fpm-alpine
    container_name: php-fpm
    restart: always
    volumes:
      - ../php/src/html:/var/www/html
      #- ../php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      default:
        aliases:
          - mis_network




