version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.2-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80
  # rust
  rust:
    image: rust:1.70
    volumes:
      - ../rust/misur:/rust/misur
    environment:
      - USER=warun12
  db:
    oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    restart: always
    environment:
      - ORACLE_SID=BISPRD
      - ORACLE_PDB=CMMARTOWN
      - ORACLE_PWD=asdf1234
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1522/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

    
