version: "3.8"
services:
  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: nginx-webserver
    restart: unless-stopped
    depends_on:
        - app
    ports:
        - "8001:80"
    volumes:
        - ./php/src:/var/www/
        - ./Dockerfiles/nginx:/etc/nginx/conf.d
    networks:
        - app-network
  db:
    oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    restart: always
    environment:
      - ORACLE_SID=BISPRD
      - ORACLE_PDB=CMMARTOWN
      - ORACLE_PWD=asdf1234
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1522/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
    app-network:
    
