version: "3.9"
services:
  
  # nginx
  web:
    image: nginx:1.25.1-alpine
    restart: unless-stopped
    ports: 
      - "8080:80"
    volumes:
      - ../php/src/html:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php-fpm
  
  php-fpm:
    image: php:8.2.5-fpm-alpine
    volumes:
      - ../php/src/html:/var/www/html
      - ../php/config/php.ini:/usr/local/etc/php/php.ini





